# Generated by Django 2.2.3 on 2019-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190802_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
